function SW = swa_initialise_struct(SW_type);

switch SW_type
    case ('ST')
        SW = struct(...
            'CWT_Start',                [],...
            'CWT_End',                  [],...
            'CWT_NegativePeak',         [],...
            'CWT_PeakToPeak',           [],...
            'CWT_ThetaAlpha',           [],...
            'Ref_Region',               [],...
            'Ref_StartInd',             [],...
            'Ref_PeakInd',              [],...
            'Ref_EndInd',               [],...
            'Ref_NegativeSlope',        [],...
            'Ref_PositiveSlope',        [],...
            'Ref_NotchAmp',             [],...
            'Burst_BurstId',            [],...
            'Burst_NumberOfWaves',      [],...
            'Burst_Density',            [],...      % Number of Waves/Second in Burst
            'Channels_Active',          [],...
            'Channels_Peak2PeakAmp',    [],...
            'Channels_Globality',       [],...
            'Channels_NegativeMax',     [],...      % Peak negative amplitude in the channels
            'Channels_PositiveMax',     [],...
            'Travelling_Delays',        [],...
            'Travelling_DelayMap',      [],...
            'Travelling_Density',       [],...
            'Travelling_Streams',       []);
        
end